### ISSUE TITLE
Sample differs from NuGet

### ISSUE THREAD

**Issue by MKahmen** [chrisriesgo/Android-AltBeacon-Library#11]
Hi Chris,

your Xamarin.Forms sample does not use the NuGet Package.
The .dll works fine but the dll from NuGet wants me to implement all methods (even Dispose and Handle):

    class Class1 : IBeaconConsumer
    {

        public Context ApplicationContext
        {
            get { throw new NotImplementedException(); }
        }

        public bool BindService(Intent intent, IServiceConnection serviceConnection, Bind flags)
        {
            throw new NotImplementedException();
        }

        public void OnBeaconServiceConnect()
        {
            throw new NotImplementedException();
        }

        public void UnbindService(IServiceConnection serviceConnection)
        {
            throw new NotImplementedException();
        }

        public IntPtr Handle
        {
            get { throw new NotImplementedException(); }
        }

        public void Dispose()
        {
            throw new NotImplementedException();
        }
    }

Even though the Versions are equal (2.7)...

BR

**Comment by MKahmen** [comment]
Seems like it was my fault. Since I did not implement `FormsAppCompatActivity` as well..
It works very good If I add `IBeaconConsumer` in my MainActivity.

Sorry for disturbing ;-)

Why do you have two versions of AltBeacons Lib in the component store?
http://components.xamarin.com/view/xamarin-android-ibeacon-service
http://components.xamarin.com/view/android-altbeacon-library

BR

**Comment by chrisriesgo** [comment]
@MKahmen - Sorry for taking so long to reply. Glad you got the problem sorted out. The reason there are 2 versions in the component store is a matter of history. 

- The `xamarin-android-ibeacon-service` was originally created by Radius Networks as a library for ranging beacons from Android -- but slanted toward Radius Networks tech. This library is no longer maintained by Radius Networks (and therefore not by me either), but I just haven't removed the library in case someone is really really needing it.
- The `android-altbeacon-library` came later. Also started by Radius Networks, this library was meant to be more open and part of a proposed beacon spec. This is the currently maintained library.
