### ISSUE TITLE
Xamarin Forms iOS example

### ISSUE THREAD

**Issue by jerone** [chrisriesgo/Android-AltBeacon-Library#19]
It looks like the [iOS Forms example](https://github.com/chrisriesgo/Android-AltBeacon-Library/tree/master/Samples/Forms/AltBeaconLibrary.Sample/iOS) is not implemented.
Do you have plans to build this version? 
It would be highly appreciated.

**Comment by panetta-net-au** [comment]
That's probably because the underlying library doesn't support iOS: https://github.com/AltBeacon/spec/issues/19

If you want to simply use iBeacons, this is built into iOS and Xamarin. See https://blog.xamarin.com/play-find-the-monkey-with-ios-7-ibeacons/

**Comment by chrisriesgo** [comment]
Thanks for responding. That's accurate. The AltBeacon spec doesn't cover iOS.

**Comment by panetta-net-au** [comment]
No problem. I've just been digging through the sample code. Perhaps @jerone was referring to the fact that the IAltBeaconService interface used in the sample was not implemented using CLLocationManager for iOS.

To answer that question more specifically, I think providing that implementation is out of the scope for this library. You'd be better off looking at the Xamarin documentation and the Xamarin blogpost I linked to above.
