### ISSUE TITLE
AltBeaconLibrary sample service start on boot

### ISSUE THREAD

**Issue by bokzy** [chrisriesgo/Android-AltBeacon-Library#2]
Based on testing on various Android 4.3 and 4.4 devices, we noticed there's an issue with running AltBeacon service upon device boot. It works fine if demo app is run by user or put into background mode. Service is started upon boot (it's visible in Android running services list) , but no events are triggered and doesn't seem to initiate either monitoring or ranging.

**Comment by chrisriesgo** [comment]
@bokzy - Let me see if I'm understanding you correctly.

1. Install demo app
2. Reboot Android device
3. AltBeacon service is started upon boot
4. You aren't able to tap into monitoring or ranging events without manually starting the client app

Is that correct?

**Comment by bokzy** [comment]
Hi Chris, thanks for your quick reply.

It's exactly as you wrote, we tried to tap into every event that should be triggered upon service startup or when beacon gets in the range, but to no avail. Service keeps running, though.

**Comment by chrisriesgo** [comment]
Hi @bokzy. I just updated the library to the latest release from AltBeacon.org - version 2.1.2. See if that helps. I'm going to try some internal testing as well.

**Comment by bokzy** [comment]
Well actually this version of demo doesn't even keep running after boot (previous one at least kept service running, although no beacon ranging occurred) .

**Comment by chrisriesgo** [comment]
@bokzy - If you're looking at Samples/Android, all I did was update the underlying library. The Sample doesn't explicitly address boot scenarios. Apparently there were some changes regarding backgrounding that may have affected how the service starts and stops when backgrounded. That may mean, that new code needs to be introduced in order for backgrounding to work like you'd expect. I'm still doing testing, but if you have additional samples that I can try, I'd be happy to try them out myself.

**Comment by chrisriesgo** [comment]
@bokzy - I have a working sample in a new branch. Please take a look:

https://github.com/chrisriesgo/Android-AltBeacon-Library/tree/updated-reference/Samples/Android/AndroidAltBeaconLibrary.Sample

Upon reboot, when a beacon becomes available, the sample app launches. Also, if the app is backgrounded, but not force-closed, and a beacon appears, a notification is sent.

It took me a while to figure out that my androidmanifest.xml wasn't correct which is probably why you didn't see the app behaving correctly to begin with. Let me know if this helps.

**Comment by chrisriesgo** [comment]
@bokzy - I'm going to close this issue since I'm able to pick up beacons upon boot. Please reference the latest Samples/Android in master.
