### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by halukmy** [chrisriesgo/Android-AltBeacon-Library#20]
any update is on the way?

**Comment by chrisriesgo** [comment]
Hi @halukmy. Which specific version of the AltBeacon library are you curious about seeing an update for?

**Comment by halukmy** [comment]
Thanks for quick reply,

i use your 2015 version, last android release is not update, and i guess there is something wrong.. it updates so slowly near and away .. there were a dude was create for glass too, its library use only 1 beacon but i guess its faster find than alt, i will be so happy if you can update latest altbeacon release for us friend,

greetings

**Comment by jerone** [comment]
The current version of AltBeacon is at [2.9.1](https://github.com/AltBeacon/android-beacon-library/releases) while this Nuget package is at 2.7.0. It includes multiple bugfixes.

**Comment by acaliaro** [comment]
Hi @chrisriesgo. I am interested too to know if you have some plans to update the library to 2.9 version. Thanks.

**Comment by AeonDave** [comment]
i'll love to see an update!
PLEASE!

**Comment by FredyFLU** [comment]
Please update the component dependencies! 
Current AltBeacon native lib is now two years old (v2.7, actually v2.9)
The last version fixes major issues under Android 7.
We are doing indoor tracking and Android is now limiting the number of times BT scan to 5 times / 30 sec, V2.9.2 avoid the issue by not stopping scans between cycles. 
(See https://github.com/AltBeacon/android-beacon-library/commit/7bfc78e044f7ea7db3b8514bcbcf51f4071524a7 for more info)

Thanks you.

**Comment by jordimasmi** [comment]
It's very important for me too; limit of times BT scan to 5 times / 30 sec is a handycap for us.

I did not know this limitation, and now I understand why the behavior of the app.
In the past we used the other library: Android iBeacon Service, and I think this limitation wasn't exist (it was another native lib)

Thanks @chrisriesgo !

**Comment by chrisriesgo** [comment]
I've started updating the library! It's not done yet, but I just published a [first-look alpha release](https://github.com/chrisriesgo/Android-AltBeacon-Library/releases/tag/v.2.10.0-alpha1) of *2.10.0*.

Download the attached *.DLL*, try it out, and let me know if you have any issues.

**Comment by chrisriesgo** [comment]
Closing this issue. Please track progress on the 2.10.0 update on Issue #25.
