### ISSUE TITLE
Update required to fix issues under Android 7

### ISSUE THREAD

**Issue by FredyFLU** [chrisriesgo/Android-AltBeacon-Library#24]
Please update the component dependencies! 
Current AltBeacon native lib is now two years old (v2.7, actually v2.9)
The last version fixes major issues under Android 7 (
2.9.2 required)

Thanks you.

**Comment by jordimasmi** [comment]
Yes, please, update to the latest native lib.
Thanks in advance !

**Comment by chrisriesgo** [comment]
I've started updating the library! It's not done yet, but I just published a [first-look alpha release](https://github.com/chrisriesgo/Android-AltBeacon-Library/releases/tag/v.2.10.0-alpha1) of *2.10.0*.

Download the attached *.DLL*, try it out, and let me know if you have any issues.

**Comment by chrisriesgo** [comment]
Closing this issue. Please track progress on the 2.10.0 update on Issue #25.
