### ISSUE TITLE
java.io.FileNotFoundException

### ISSUE THREAD

**Issue by MAX-POLKOVNIK** [chrisriesgo/Android-AltBeacon-Library#3]
I Just run sample. Device Nexus 5. Android 5.1. 

03-19 12:11:25.311 E/ModelSpecificDistanceCalculator( 7851): Cannot open distance model file /data/data/TestAltBeacon.TestAltBeacon/files/model-distance-calculations.json
03-19 12:11:25.311 E/ModelSpecificDistanceCalculator( 7851): java.io.FileNotFoundException: /data/data/TestAltBeacon.TestAltBeacon/files/model-distance-calculations.json: open failed: ENOENT (No such file or directory)
03-19 12:11:25.311 E/ModelSpecificDistanceCalculator( 7851): 	at libcore.io.IoBridge.open(IoBridge.java:456)
03-19 12:11:25.311 E/ModelSpecificDistanceCalculator( 7851): 	at java.io.FileInputStream.<init>(FileInputStream.java:76)
03-19 12:11:25.311 E/ModelSpecificDistanceCalculator( 7851): 	at org.altbeacon.beacon.distance.ModelSpecificDistanceCalculator.loadModelMapFromFile(ModelSpecificDistanceCalculator.java:152)
03-19 12:11:25.311 E/ModelSpecificDistanceCalculator( 7851): 	at org.altbeacon.beacon.distance.ModelSpecificDistanceCalculator.loadModelMap(ModelSpecificDistanceCalculator.java:132)
03-19 12:11:25.311 E/ModelSpecificDistanceCalculator( 7851): 	at org.altbeacon.beacon.distance.ModelSpecificDistanceCalculator.<init>(ModelSpecificDistanceCalculator.java:72)
03-19 12:11:25.311 E/ModelSpecificDistanceCalculator( 7851): 	at org.altbeacon.beacon.distance.ModelSpecificDistanceCalculator.<init>(ModelSpecificDistanceCalculator.java:62)
03-19 12:11:25.311 E/ModelSpecificDistanceCalculator( 7851): 	at org.altbeacon.beacon.service.BeaconService.onCreate(BeaconService.java:205)
03-19 12:11:25.311 E/ModelSpecificDistanceCalculator( 7851): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2761)
03-19 12:11:25.311 E/ModelSpecificDistanceCalculator( 7851): 	at android.app.ActivityThread.access$1800(ActivityThread.java:151)
03-19 12:11:25.311 E/ModelSpecificDistanceCalculator( 7851): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1386)
03-19 12:11:25.311 E/ModelSpecificDistanceCalculator( 7851): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-19 12:11:25.311 E/ModelSpecificDistanceCalculator( 7851): 	at android.os.Looper.loop(Looper.java:135)
03-19 12:11:25.311 E/ModelSpecificDistanceCalculator( 7851): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
03-19 12:11:25.311 E/ModelSpecificDistanceCalculator( 7851): 	at java.lang.reflect.Method.invoke(Native Method)
03-19 12:11:25.311 E/ModelSpecificDistanceCalculator( 7851): 	at java.lang.reflect.Method.invoke(Method.java:372)
03-19 12:11:25.311 E/ModelSpecificDistanceCalculator( 7851): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
03-19 12:11:25.311 E/ModelSpecificDistanceCalculator( 7851): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
03-19 12:11:25.311 E/ModelSpecificDistanceCalculator( 7851): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
03-19 12:11:25.311 E/ModelSpecificDistanceCalculator( 7851): 	at libcore.io.Posix.open(Native Method)
03-19 12:11:25.311 E/ModelSpecificDistanceCalculator( 7851): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
03-19 12:11:25.311 E/ModelSpecificDistanceCalculator( 7851): 	at libcore.io.IoBridge.open(IoBridge.java:442)
03-19 12:11:25.311 E/ModelSpecificDistanceCalculator( 7851): 	... 16 more

**Comment by chrisriesgo** [comment]
Thanks, @MAX-POLKOVNIK. This is a bug in version 2.1.3 of the underlying library.

https://github.com/AltBeacon/android-beacon-library/issues/124

It shouldn't cause you problems, but I believe it was fixed in version 2.1.4 which I hope to update my library to soon.

**Comment by chrisriesgo** [comment]
@MAX-POLKOVNIK - FYI, I've updated the library to [2.1.4](https://github.com/chrisriesgo/Android-AltBeacon-Library/releases/tag/2.1.4)
