### ISSUE TITLE
Exception in sample App.

### ISSUE THREAD

**Issue by MAX-POLKOVNIK** [chrisriesgo/Android-AltBeacon-Library#4]
Just run sample. Samsung Galaxy S5. Android 5.0

03-19 17:16:34.569 E/mono    (30193): Unhandled Exception:
03-19 17:16:34.569 E/mono    (30193): System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
03-19 17:16:34.569 E/mono    (30193):   at System.Collections.Generic.List`1+Enumerator[AltBeaconOrg.BoundBeacon.Beacon].MoveNext () [0x00000] in <filename unknown>:0 
03-19 17:16:34.569 E/mono    (30193):   at System.Linq.Enumerable.All[Beacon] (IEnumerable`1 source, System.Func`2 predicate) [0x00000] in <filename unknown>:0 
03-19 17:16:34.569 E/mono    (30193):   at AndroidAltBeaconLibrary.Sample.MainActivity+<>c__DisplayClass20.<UpdateData>b__1c () [0x00003] in c:\Users\POLKOVNIK\Documents\Android-AltBeacon-Library\Samples\Android\AndroidAltBeaconLibrary.Sample\MainActivity.cs:259 
03-19 17:16:34.569 E/mono    (30193):   at System.Threading.Tasks.TaskActionInvoker+ActionInvoke.Invoke (System.Threading.Tasks.Task owner, System.Object state, System.Threading.Tasks.Task context) [0x00000] in <filename unknown>:0 
03-19 17:16:34.569 E/mono    (30193):   at System.Threading.Tasks.Task.InnerInvoke () [0x00000] in <filename unknown>:0 
03-19 17:16:34.569 E/mono    (30193):   at System.Threading.Tasks.Task.ThreadStart () [0x00000] in <filename unknown>:0 
03-19 17:16:34.569 E/mono    (30193): --- End of stack trace from previous location where exception was thrown ---
03-19 17:16:34.569 E/mono    (30193):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
03-19 17:16:34.569 E/mono    (30193):   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>:0 
03-19 17:16:34.569 E/mono    (30193):   at AndroidAltBeaconLibrary.Sample.MainActivity+<UpdateData>d__24.MoveNext () [0x0004c] in c:\Users\POLKOVNIK\Documents\Android-AltBeacon-Library\Samples\Android\AndroidAltBeaconLibrary.Sample\MainActivity.cs:257 
03-19 17:16:34.569 E/mono    (30193): --- End of stack trace from previous location where exception was thrown ---
03-19 17:16:34.569 E/mono    (30193):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
03-19 17:16:34.569 E/mono    (30193):   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>:0 
03-19 17:16:34.569 E/mono    (30193):   at AndroidAltBeaconLibrary.Sample.MainActivity+<>c__DisplayClass7+<<RangingBeaconsInRegion>b__5>d__9.MoveNext () [0x00031] in c:\Users\POLKOVNIK\Documents\Android-AltBeacon-Library\Samples\Android\AndroidAltBeaconLibrary.Sample\MainActivity.cs:184 
The thread 'Unknown' (0x7) has exited with code 0 (0x0).

**Comment by chrisriesgo** [comment]
Thanks for the heads up @MAX-POLKOVNIK. I'm improperly modifying the collection while iterating over it.

**Comment by chrisriesgo** [comment]
@MAX-POLKOVNIK - Just pushed a fix to the Xamarin.Android sample. Hope that helps.
