### ISSUE TITLE
Ranging beacon reporting bad results

### ISSUE THREAD

**Issue by rusty21** [chrisriesgo/Android-AltBeacon-Library#7]
I am attempting to range beacons for a short amount of time while the app is open. I have set up a range notifier and I do get notifications when the beacons are ranged. The problem I'm having is when I have a beacon in range (sitting inches away from the phone) the range notifier will report 1 beacon in range, and then the next update it will report 0. It constantly flips back and forth between 0,1,0,1. The beacon and phone are clearly close enough together so I'm certain the signal strength is not an issue. This seems to be pretty consistent too. Any ideas? Maybe I'm doing something wrong?

**Comment by chrisriesgo** [comment]
@rusty21 - I used to see this all the time too, and was sure that I was doing something wrong. I'd have to dig around in the original library, but this is normal behavior. The library's itself doesn't compensate for this phenomenon. The suggestion is to build a sort of ranging engine yourself where if you find a beacon, log it, and even if the next pass doesn't see it, keep it around until it hasn't been seen in [some amount of time or number of iterations].

Does that help at all?
